<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDL0AgnY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDL0AgnY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDL0AgnY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDL0AgnY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDL0AgnY\App_KernelDevDebugContainer([
    'container.build_hash' => 'DL0AgnY',
    'container.build_id' => '49e5c958',
    'container.build_time' => 1673630365,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDL0AgnY');
