<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDFXQmnV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDFXQmnV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDFXQmnV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDFXQmnV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDFXQmnV\App_KernelDevDebugContainer([
    'container.build_hash' => 'DFXQmnV',
    'container.build_id' => '8d0936db',
    'container.build_time' => 1673630573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDFXQmnV');
