<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_tacos_rendertacos' => [[], ['_controller' => 'App\\Controller\\TacosController::renderTacos'], [], [['text', '/']], [], [], []],
    'app_tacos_filtertacos' => [['collection'], ['_controller' => 'App\\Controller\\TacosController::filterTacos'], [], [['variable', '/', '[^/]++', 'collection', true]], [], [], []],
    'app_tacos_goto' => [[], ['_controller' => 'App\\Controller\\TacosController::goto'], [], [['text', '/goto/credits']], [], [], []],
    'app_tacos_accueil' => [[], ['_controller' => 'App\\Controller\\TacosController::accueil'], [], [['text', '/templates/accueil.html.twig']], [], [], []],
];
