<?php

namespace ContainerVxMX5EB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C_YszV0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C.yszV0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C.yszV0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'credits' => ['privates', 'App\\Service\\CreditsInterface', 'getCreditsInterfaceService', true],
        ], [
            'credits' => 'App\\Service\\CreditsInterface',
        ]);
    }
}
