<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXk8B0Fb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXk8B0Fb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXk8B0Fb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXk8B0Fb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXk8B0Fb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xk8B0Fb',
    'container.build_id' => 'bbf4e6b2',
    'container.build_time' => 1673630886,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXk8B0Fb');
